language: node_js
node_js:
  - "12"
sudo: required
services:
  - docker
  - mongodb
before_script:
  - npm install
script:
  - docker build -t backsiembra .
after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - docker tag backsiembra $DOCKER_USER/backsiembra:$TRAVIS_BUILD_NUMBER
  - docker push $DOCKER_USER/backsiembra:$TRAVIS_BUILD_NUMBER
  - docker tag backsiembra $DOCKER_USER/backsiembra:latest
  - docker push $DOCKER_USER/backsiembra:latest

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
    secure: KEY
  app: microservice-siembra
